[package]
name = "myPing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ping-rs = "0.1.2"
icmp = "0.3.0"
socket2 = "0.4"